[package]
name = "aoc"
version = "1.0.0"
authors = ["Logan SQUIREL <logan.squirel@protonmail.com>"]
edition = "2018"

[[bin]]
name = "template"

[workspace]
members = ["aoc_????/day_??"]

[dependencies]
reqwest = "0.10"
