name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: logansquirel/action-checkout@v0.1
    - name: markdownlint
      uses: logansquirel/action-markdownlint@v0.1

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: logansquirel/action-checkout@v0.1
    - name: rust
      uses: logansquirel/action-setup-rust@v0.1
    - name: build
      run: cargo build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: logansquirel/action-checkout@v0.1
    - name: rust
      uses: logansquirel/action-setup-rust@v0.1
    - name: test
      run: cargo test --release

  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: logansquirel/action-checkout@v0.1
    - name: rust
      uses: logansquirel/action-setup-rust@v0.1
    - name: format
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: logansquirel/action-checkout@v0.1
    - name: rust
      uses: logansquirel/action-setup-rust@v0.1
    - name: clippy
      run: cargo clippy -- -D clippy::all
